### ISSUE TITLE
[META TOPIC] Design Inspiration

### ISSUE THREAD

**Issue by cerisier** [pathwar/portal.pathwar.net#46]
Let's list all sort of inspiration: Design, Product, Details.

**Comment by cerisier** [comment]
https://www.dropbox.com/s/qvubo4hrbru0coi/Screenshot%202015-02-03%2000.26.48.png?dl=0

**Comment by cerisier** [comment]
TreeHouse has a great layout.

![screenshot 2015-02-03 00 26 48](https://www.dropbox.com/s/qvubo4hrbru0coi/Screenshot%202015-02-03%2000.26.48.png?dl=1)

**Comment by moul** [comment]
I personally hate full-width designs on computers

**Comment by cerisier** [comment]
That's because you have a 30 inch screen :stuck_out_tongue: 
We could do a max-width thing to prevent looking shit on huge displays

**Comment by moul** [comment]
That's because an application won't be optimized for each resolutions (30 inch, 13 inch, tablet, mobile) on fluid design without per-resolution optimizations
I do prefer a fixed design and play with html5 zoom capabilities

Also if we choose something fluid/fixed, I greatly recommend the mobile-first rule
